# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{steak}
  s.version = "0.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Luismi Cavall\303\251"]
  s.date = %q{2010-01-01}
  s.description = %q{Acceptance specs for Rails}
  s.email = %q{luismi@lmcavalle.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "README.rdoc",
     "generators/acceptance_spec/USAGE",
     "generators/acceptance_spec/acceptance_spec_generator.rb",
     "generators/acceptance_spec/templates/acceptance_spec.rb",
     "generators/steak/USAGE",
     "generators/steak/steak_generator.rb",
     "generators/steak/templates/acceptance_helper.rb",
     "generators/steak/templates/helpers.rb",
     "generators/steak/templates/paths.rb",
     "generators/steak/templates/steak.rake",
     "lib/steak.rb"
  ]
  s.homepage = %q{http://github.com/cavalle/steak}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{A steak is a cucumber fermented in vinegar or brine}
  s.test_files = [
    "spec/acceptance/acceptance_helper.rb",
     "spec/acceptance/acceptance_spec_generator_spec.rb",
     "spec/acceptance/basic_spec.rb",
     "spec/acceptance/rails_spec.rb",
     "spec/acceptance/steak_generator_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

